apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-hpa
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
